### ISSUE TITLE
Call migration file during seed:install instead

### ISSUE THREAD

**Issue by mayppong** [slampenny/SmartSeeder#13]
I see there is a migration file set up for the seeds table. Why not use that instead of coding the table structure right in the SmartSeedRepository?

**Comment by slampenny** [comment]
This uses the same method as Laravel's migrator (which this mimics). You can verify this in the illuminate code if you'd like.

As a side note, I dislike the concept of package migrations anyways, since the users always has to remember to migrate them separately or everything breaks.

**Comment by mayppong** [comment]
So .. the migration file should be remove then?
