### ISSUE TITLE
Add option to specify a seed file to be run individually

### ISSUE THREAD

**Issue by marlongichie** [slampenny/SmartSeeder#17]
By default, the `seed:run` command runs all the seed classes. 

However, it would be useful to be able to use the `--class` option to specify a specific seeder class to run individually. Much like the functionality provided by Laravel's out of the box seeding.

This could look something like:

```
php artisan seed:run --class=UserSeeder
```

or 

```
php artisan seed:run --class=seed_2015_06_23_002940_UserSeeder
```

**Comment by slampenny** [comment]
This is a great suggestion. I don't have a lot of time right now and would appreciate a pull request, but if you can't do it either I'll try and implement it soon.

**Comment by slampenny** [comment]
@marlongichie This is now done. use the --file option

**Comment by marlongichie** [comment]
Great work! Thank you for this.
