### ISSUE TITLE
add path option through artisan command for seed location.

### ISSUE THREAD

**Issue by umefarooq** [slampenny/SmartSeeder#6]
really nice package really easy way to create, run, install seeds i have check the code seeds path is define in config, can you add an option in package of providing path of the seed desire location, if that path options is not available then it can take config path. this will help other package developers to create new commands for creating seeds on other location they will call your commands with in their package commands no need to reinvent the wheel again,

**Comment by deviarte** [comment]
+1 - I was just about to ask the same question!

**Comment by slampenny** [comment]
Sorry, I didn't see this issue until now. I'll try and have something by early next week.

**Comment by umefarooq** [comment]
thanks for checking this request.

**Comment by slampenny** [comment]
I think this option already exists? You can change the seedDir value in the config folder. If you don't your seeds go in the database folder (where laravel's default seeds go) but in the smartSeeds folder.

Please clarify if this is not what you mean.

**Comment by mayppong** [comment]
We actually develop our app in a modular format. During the deployment, we decide the modules we need, and publish the seed files from those deployed modules into the smartSeeds' config folder.

The ability to create a seed file in a specified path and run only seeds found in a specified path help us the development process greatly.

I've created a merge request for specifying the path when making a new seed file. There's the step 1.

**Comment by slampenny** [comment]
@umefarooq , May's pull request fixing this issue has been merged.
